### ISSUE TITLE
OSM digitising progress update (map)

### ISSUE THREAD

**Issue by alxpapadaki** [FruitsofThought/ngambomap#19]
We need at this point a map that shows coloured which buildings we have surveyed so far. We need this asap to be able to research for missing parts and proceed to decision making for the completion of the mapping.

Marieke? Do you know how to do this quickly?

**Comment by batje** [comment]
I just re-exported the OSM data in QGIS. It is both on Dropbox as well as in git.

If you want to see it quickly for yourself, you can also download the whole area in Josm and then do Edit > Find

building:architecture:typology=*

That will select all houses that have that attribute
(better would be building=yes, that would give you all buildings we do _not_ know of what is happening there. Unfortunately it seems this has not been recorded consistently so far.)

**Comment by batje** [comment]
So closing.

**Comment by alxpapadaki** [comment]
I did exported today from osm in qgis and made a pdf. already sent to the team (you should have a copy as well)
