### ISSUE TITLE
Remove 'Timber Frame and Metal Sheets' from Building Structure

### ISSUE THREAD

**Issue by batje** [FruitsofThought/ngambomap#9]

**Comment by MariekeOosterom** [comment]
done

**Comment by batje** [comment]
There were a LOT of conflicts between the fix set from Alexandra and these corrections, so I had to rewind this edit in order to upload. Sorry, can you refix this (it is not documented what was done, so i can not redo it)
(even worse: this house was never fixed:
https://www.openstreetmap.org/way/382855721/history
)

**Comment by MariekeOosterom** [comment]
I changed it again

**Comment by batje** [comment]
fixed
